server:
  port:
    8081

security:
  oauth2:
    jwt:
      signkey: 123@#$
    #클라이언트 정보와 token-info-uri 만으로 토큰 체크가 가능
#    resource:
#      token-info-uri: http://localhost:8080/oauth/check_token
#    client:
#      client-id: foo
#      client-secret: bar

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootex
    username: bootex
    password: bootex
    driver-class-name: com.mysql.cj.jdbc.Driver
